"""Generate manuscript tables and macros from the independent audit (stdlib only).

Run audit_evidence.py first to reanalyse the original recordings. This script
reads only that JSON summary and writes only paper-astra/generated/.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "analysis/outputs/evidence-audit.json"
OUT = PAPER / "generated"


def main():
    audit = json.loads(SOURCE.read_text())
    cohort, sessions = audit["cohort"], audit["sessions"]
    if (cohort["participants"], cohort["sessions"]) != (4, 8):
        raise ValueError("Cohort changed: revise the manuscript before regenerating tables")
    if len(audit["advisory"]) != 1:
        raise ValueError("Expected one separately analysed advisory recording")
    if not all(r["telemetry_session_and_times_match"] for r in audit["integrity"]):
        raise ValueError("A session/telemetry join failed")
    OUT.mkdir(exist_ok=True)
    header = "% Generated by analysis/build_paper_assets.py; do not edit by hand.\n"

    def save(name, rows):
        (OUT / name).write_text(header + "\n".join(rows) + "\n")

    def table_row(*cells):
        return " & ".join(str(c) for c in cells) + r" \\"

    def save_table(name, columns, headings, rows):
        # Keep the whole alignment in one input file: LaTeX's file hooks may
        # otherwise insert material between the final row and booktabs rules.
        save(name, [rf"\begin{{tabular}}{{{columns}}}", r"\toprule",
                    table_row(*headings), r"\midrule", *rows,
                    r"\bottomrule", r"\end{tabular}"])

    def number(value, precision=1):
        return f"{value:.{precision}f}".rstrip("0").rstrip(".") if precision else str(round(value))

    fixations = sum(s["fixations"] for s in sessions)
    saccades = sum(s["saccades"] for s in sessions)
    dfix = sum(s["duplicate_fixation_payloads"] for s in audit["integrity"])
    dsac = sum(s["duplicate_saccade_payloads"] for s in audit["integrity"])
    values = {
        "gazeTotal": f'{cohort["gaze_samples"]:,}',
        "gazeMeanHz": f'{cohort["session_mean_hz"]:.2f}',
        "gazeSdHz": f'{cohort["session_sd_hz"]:.2f}',
        "gazeMinHz": f'{min(s["hz"] for s in sessions):.2f}',
        "gazeMaxHz": f'{max(s["hz"] for s in sessions):.2f}',
        "gazeMeanValid": f'{cohort["session_mean_validity_pct"]:.2f}',
        "gazeMinValid": f'{min(s["validity_pct"] for s in sessions):.2f}',
        "gazeMaxValid": f'{max(s["validity_pct"] for s in sessions):.2f}',
        "fixationTotal": f"{fixations:,}", "saccadeTotal": f"{saccades:,}",
        "duplicateFixations": str(dfix), "duplicateSaccades": str(dsac),
        "duplicateFixationPct": f"{100*dfix/fixations:.1f}",
        "duplicateSaccadePct": f"{100*dsac/saccades:.1f}",
    }
    save("results.tex", [rf"\newcommand{{\{key}}}{{{value}}}" for key, value in values.items()])
    labels = {"with": r"\on{}", "without": r"\off{}"}
    texts = {"Metal Detectors": "M", "Nuclear Science": "N"}
    save_table("session-table.tex", "lllrrrrr",
        ["Participant", "Condition", "Text", "Duration (s)", "Gaze samples", "Rate (Hz)", r"Valid (\%)", "Changes"], [table_row(
        s["participant"], labels[s["condition"]], texts[s["text_title"]],
        f'{s["duration_s"]:.1f}', f'{s["gaze_samples"]:,}', f'{s["hz"]:.2f}',
        f'{s["validity_pct"]:.2f}', s["interventions"])
        for s in sorted(sessions, key=lambda s: (s["participant"], s["condition"]))])

    latency = audit["advisory"][0]["latency"]
    populations = [
        ("Eight sessions", "Participant-client RTT", audit["cohort_rtt"]["participant"]),
        ("Eight sessions", "Researcher-client RTT", audit["cohort_rtt"]["researcher"]),
        ("Advisory run", "Participant-client RTT", latency["participant"]),
        ("Advisory run", "Researcher-client RTT", latency["researcher"]),
        ("Advisory run", "Dispatch-time gaze freshness", latency["pipeline-decision"]),
        ("Advisory run", "Decision-provider RTT", latency["decision-provider-rtt"]),
    ]
    save_table("timing-table.tex", "llrrrr",
        ["Recording", "Endpoint", "$n$", "Median", "95th pct.", "Maximum"], [table_row(pop, label, f'{s["n"]:,}',
        number(s["p50"]), number(s["p95"], 2), number(s["max"]))
        for pop, label, s in populations])

    original, revised = (audit["sweep"][v] for v in ("original", "revised"))
    geometry = []
    for label, field in (("Scheduled trials", "scheduled_trials"), ("Complete pairs", "measurable_pairs")):
        geometry.append(table_row(label, original[field], revised[field]))
    for condition in ("off", "on"):
        geometry.append(table_row(rf"\{condition}{{}} displacement, px ($n$)",
            *(f'{s[f"{condition}_median_px"]:.2f} ({s[f"{condition}_observed"]})'
              for s in (original, revised))))
    geometry.append(table_row("Over-repositioned", *(f'{s["over_reposition_n"]}/{s["measurable_pairs"]}'
                                               for s in (original, revised))))
    save_table("geometry-table.tex", "lrr", ["Measure", "Original", "Revised"], geometry)

    behaviour = {(s["participant"], s["condition"]): s for s in audit["participant_behaviour"]}
    rows = []
    for pid in ("P1", "P2", "P3", "P4"):
        a, b = behaviour[(pid, "with")], behaviour[(pid, "without")]
        rows.append(table_row(pid,
            f'{number(a["rrt_median_ms"])} ({a["rrt_observed"]}/{a["interventions"]})',
            f'{number(b["rrt_median_ms"])} ({b["rrt_observed"]}/{b["interventions"]})'))
    save_table("behaviour-table.tex", "lrr",
        ["Participant", r"\on{}: ms ($n/N$)", r"\off{}: ms ($n/N$)"], rows)
    manifest = {"source": "analysis/outputs/evidence-audit.json",
                "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                "source_review_commit": audit["review_commit"],
                "generated_files": sorted(p.name for p in OUT.glob("*.tex"))}
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Generated {len(manifest['generated_files'])} LaTeX assets from audited evidence.")


if __name__ == "__main__":
    main()
