"""Generate manuscript tables and macros from the independent audit (stdlib only).

Origin: paper-astra/analysis/build_paper_assets.py, extended for the merged
manuscript with additional macros (behaviour, timing, calibration, context
outcomes, sweep) and a per-intervention sweep table.
Run audit_evidence.py first to reanalyse the original recordings. This script
reads only that JSON summary and writes only paper-merged/generated/.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "analysis/outputs/evidence-audit.json"
OUT = PAPER / "generated"

SWEEP_LABELS = {
    "Font size +2px (18->20)": r"Font size $+2$\,px (18 to 20)",
    "Font size +6px (18->24)": r"Font size $+6$\,px (18 to 24)",
    "Font size -2px (18->16)": r"Font size $-2$\,px (18 to 16)",
    "Line height +0.3 (1.8->2.1)": r"Line height $+0.3$ (1.8 to 2.1)",
    "Line height -0.3 (1.8->1.5)": r"Line height $-0.3$ (1.8 to 1.5)",
    "Line width -120px (680->560)": r"Line width $-120$\,px (680 to 560)",
    "Line width +80px (680->760)": r"Line width $+80$\,px (680 to 760)",
    "Letter spacing +0.06em": r"Letter spacing $+0.06$\,em",
    "Letter spacing +0.12em": r"Letter spacing $+0.12$\,em",
    "Font family -> Inter": r"Font family to Inter",
    "Font family -> Space Grotesk": r"Font family to Space Grotesk",
}


def main():
    audit = json.loads(SOURCE.read_text())
    cohort, sessions = audit["cohort"], audit["sessions"]
    if (cohort["participants"], cohort["sessions"]) != (4, 8):
        raise ValueError("Cohort changed: revise the manuscript before regenerating tables")
    if len(audit["advisory"]) != 1:
        raise ValueError("Expected one separately analysed advisory recording")
    if not all(r["telemetry_session_and_times_match"] for r in audit["integrity"]):
        raise ValueError("A session/telemetry join failed")
    OUT.mkdir(exist_ok=True)
    header = "% Generated by analysis/build_paper_assets.py; do not edit by hand.\n"

    def save(name, rows):
        (OUT / name).write_text(header + "\n".join(rows) + "\n")

    def table_row(*cells):
        return " & ".join(str(c) for c in cells) + r" \\"

    def save_table(name, columns, headings, rows, midrules=()):
        # Keep the whole alignment in one input file: LaTeX's file hooks may
        # otherwise insert material between the final row and booktabs rules.
        body = []
        for i, row in enumerate(rows):
            if i in midrules:
                body.append(r"\midrule")
            body.append(row)
        save(name, [rf"\begin{{tabular}}{{{columns}}}", r"\toprule",
                    table_row(*headings), r"\midrule", *body,
                    r"\bottomrule", r"\end{tabular}"])

    def number(value, precision=1):
        return f"{value:.{precision}f}".rstrip("0").rstrip(".") if precision else str(round(value))

    def pct(fraction, precision=1):
        return f"{100*fraction:.{precision}f}"

    fixations = sum(s["fixations"] for s in sessions)
    saccades = sum(s["saccades"] for s in sessions)
    dfix = sum(s["duplicate_fixation_payloads"] for s in audit["integrity"])
    dsac = sum(s["duplicate_saccade_payloads"] for s in audit["integrity"])
    behaviour, dedup = audit["behaviour"], audit["duplicate_payload_sensitivity"]
    rtt = audit["cohort_rtt"]
    adv = audit["advisory"][0]
    latency = adv["latency"]
    context = audit["context_by_status"]
    original, revised, cross = (audit["sweep"][k] for k in ("original", "revised", "cross_version"))
    order = audit["condition_order"]
    with_first = sum(v[0] == "with" for v in order.values())

    values = {
        "participantsN": str(cohort["participants"]),
        "sessionsN": str(cohort["sessions"]),
        "gazeTotal": f'{cohort["gaze_samples"]:,}',
        "gazeMeanHz": f'{cohort["session_mean_hz"]:.2f}',
        "gazeSdHz": f'{cohort["session_sd_hz"]:.2f}',
        "gazeMinHz": f'{min(s["hz"] for s in sessions):.2f}',
        "gazeMaxHz": f'{max(s["hz"] for s in sessions):.2f}',
        "gazeMeanValid": f'{cohort["session_mean_validity_pct"]:.1f}',
        "gazeMinValid": f'{min(s["validity_pct"] for s in sessions):.1f}',
        "gazeMaxValid": f'{max(s["validity_pct"] for s in sessions):.1f}',
        "calAccMin": f'{min(s["accuracy_deg"] for s in sessions):.2f}',
        "calAccMax": f'{max(s["accuracy_deg"] for s in sessions):.2f}',
        "calPrecMin": f'{min(s["precision_deg"] for s in sessions):.2f}',
        "calPrecMax": f'{max(s["precision_deg"] for s in sessions):.2f}',
        "fixationTotal": f"{fixations:,}", "saccadeTotal": f"{saccades:,}",
        "duplicateFixations": str(dfix), "duplicateSaccades": str(dsac),
        "duplicateFixationPct": f"{100*dfix/fixations:.1f}",
        "duplicateSaccadePct": f"{100*dsac/saccades:.1f}",
        "interventionsWith": str(behaviour["with"]["interventions"]),
        "interventionsWithout": str(behaviour["without"]["interventions"]),
        "interventionsTotal": str(behaviour["with"]["interventions"] + behaviour["without"]["interventions"]),
        "orderWithFirst": str(with_first),
        "orderWithoutFirst": str(len(order) - with_first),
        "rrtWithMedian": number(behaviour["with"]["rrt_median_ms"], 0),
        "rrtWithMean": number(behaviour["with"]["rrt_mean_ms"], 0),
        "rrtWithObserved": str(behaviour["with"]["rrt_observed"]),
        "rrtWithoutMedian": number(behaviour["without"]["rrt_median_ms"], 0),
        "rrtWithoutMean": number(behaviour["without"]["rrt_mean_ms"], 0),
        "rrtWithoutObserved": str(behaviour["without"]["rrt_observed"]),
        "regWithPre": pct(behaviour["with"]["pre_rate_event_mean"]),
        "regWithPost": pct(behaviour["with"]["post_rate_event_mean"]),
        "regWithoutPre": pct(behaviour["without"]["pre_rate_event_mean"]),
        "regWithoutPost": pct(behaviour["without"]["post_rate_event_mean"]),
        "regWithPreDedup": pct(dedup["with"]["pre_rate_event_mean"]),
        "regWithPostDedup": pct(dedup["with"]["post_rate_event_mean"]),
        "regWithoutPreDedup": pct(dedup["without"]["pre_rate_event_mean"]),
        "regWithoutPostDedup": pct(dedup["without"]["post_rate_event_mean"]),
        "rttParticipantN": str(rtt["participant"]["n"]),
        "rttParticipantMedian": number(rtt["participant"]["p50"]),
        "rttParticipantPninefive": number(rtt["participant"]["p95"], 2),
        "rttParticipantMax": number(rtt["participant"]["max"]),
        "rttResearcherN": str(rtt["researcher"]["n"]),
        "rttResearcherMedian": number(rtt["researcher"]["p50"]),
        "rttResearcherPninefive": number(rtt["researcher"]["p95"], 2),
        "rttResearcherMax": number(rtt["researcher"]["max"]),
        "rttCohortN": str(rtt["participant"]["n"] + rtt["researcher"]["n"]),
        "rttCohortOverBudget": str(rtt["participant"]["over_100ms_n"] + rtt["researcher"]["over_100ms_n"]),
        "advDurationS": number(adv["duration_s"]),
        "advGazeSamples": f'{adv["gaze_samples"]:,}',
        "advFreshnessN": f'{latency["pipeline-decision"]["n"]:,}',
        "advFreshnessMedian": number(latency["pipeline-decision"]["p50"]),
        "advFreshnessPninefive": number(latency["pipeline-decision"]["p95"]),
        "advFreshnessMax": number(latency["pipeline-decision"]["max"]),
        "advProviderN": str(latency["decision-provider-rtt"]["n"]),
        "advProviderMedian": number(latency["decision-provider-rtt"]["p50"]),
        "advProviderMax": number(latency["decision-provider-rtt"]["max"]),
        "advParticipantN": str(latency["participant"]["n"]),
        "advParticipantMax": number(latency["participant"]["max"]),
        "advParticipantOverBudget": str(latency["participant"]["over_100ms_n"]),
        "advProposalRecords": str(adv["decision_proposal_records"]),
        "advUniqueProposals": str(adv["unique_proposal_ids"]),
        "advProposalsApproved": str(adv["proposal_record_statuses"].get("approved", 0)),
        "advProposalsSuperseded": str(adv["proposal_record_statuses"].get("superseded", 0)),
        "cpPreserved": str(context.get("preserved", {}).get("n", 0)),
        "cpDegraded": str(context.get("degraded", {}).get("n", 0)),
        "cpDegradedResidualMedian": number(context["degraded"]["anchor_error_median_px"], 0),
        "cpDegradedInducedMedian": number(context["degraded"]["viewport_delta_median_px"]),
        "sweepTrials": str(original["scheduled_trials"]),
        "sweepPairsOriginal": str(original["measurable_pairs"]),
        "sweepPairsRevised": str(revised["measurable_pairs"]),
        "sweepOverOriginal": str(original["over_reposition_n"]),
        "sweepOverRevised": str(revised["over_reposition_n"]),
        "sweepOffMedianOriginal": number(original["off_median_px"]),
        "sweepOffMedianRevised": number(revised["off_median_px"]),
        "sweepOnMedianOriginal": number(original["on_median_px"]),
        "sweepOnMedianRevised": number(revised["on_median_px"]),
        "sweepAnchorDiff": str(cross["anchor_id_differences"]),
        "sweepOffDiff": str(cross["off_displacement_diff_over_1px"]),
    }
    save("results.tex", [rf"\newcommand{{\{key}}}{{{value}}}" for key, value in values.items()])

    labels = {"with": r"\on{}", "without": r"\off{}"}
    texts = {"Metal Detectors": "M", "Nuclear Science": "N"}
    save_table("session-table.tex", "@{}lllrrrrr@{}",
        ["Participant", "Preservation", "Text", "Duration (s)", "Gaze samples", "Rate (Hz)", r"Valid (\%)", "Interventions"], [table_row(
        s["participant"], labels[s["condition"]], texts[s["text_title"]],
        f'{s["duration_s"]:.1f}', f'{s["gaze_samples"]:,}', f'{s["hz"]:.2f}',
        f'{s["validity_pct"]:.1f}', s["interventions"])
        for s in sorted(sessions, key=lambda s: (s["participant"], s["condition"]))])

    populations = [
        ("Eight sessions", "Participant-client round trip", rtt["participant"]),
        ("Eight sessions", "Researcher-client round trip", rtt["researcher"]),
        ("Advisory run", "Participant-client round trip", latency["participant"]),
        ("Advisory run", "Researcher-client round trip", latency["researcher"]),
        ("Advisory run", "Gaze freshness at decision dispatch", latency["pipeline-decision"]),
        ("Advisory run", "Decision-provider round trip", latency["decision-provider-rtt"]),
    ]
    save_table("timing-table.tex", "@{}llrrrr@{}",
        ["Recording", "Quantity (ms)", "$n$", "Median", "95th pct.", "Max."], [table_row(pop, label, f'{s["n"]:,}',
        number(s["p50"]), number(s["p95"], 2), number(s["max"]))
        for pop, label, s in populations], midrules=(2,))

    geometry = []
    for label, field in (("Scheduled trials", "scheduled_trials"), ("Complete on/off pairs", "measurable_pairs")):
        geometry.append(table_row(label, original[field], revised[field]))
    for condition, name in (("off", r"\off{} displacement, px ($n$)"), ("on", r"\on{} displacement, px ($n$)")):
        geometry.append(table_row(name,
            *(f'{s[f"{condition}_median_px"]:.1f} ({s[f"{condition}_observed"]})'
              for s in (original, revised))))
    geometry.append(table_row("Over-repositioned pairs", *(f'{s["over_reposition_n"]}/{s["measurable_pairs"]}'
                                                    for s in (original, revised))))
    save_table("geometry-table.tex", "@{}lrr@{}", ["Measure", "Original run", "Revised run"], geometry)

    def cell(entry, condition):
        median, n = entry[f"{condition}_median_px"], entry[f"{condition}_n"]
        text = f"{median:.1f}" if median is not None else "n/a"
        return text + (r"$^{*}$" if n < 6 else "")
    per_original = {e["intervention"]: e for e in original["per_intervention"]}
    per_revised = {e["intervention"]: e for e in revised["per_intervention"]}
    rows = [table_row(SWEEP_LABELS.get(label, label.replace("->", "to")),
                      cell(per_original[label], "off"), cell(per_original[label], "on"),
                      cell(per_revised[label], "off"), cell(per_revised[label], "on"))
            for label in per_original]
    rows.append(table_row(r"\textbf{All trials}",
                          *(rf"\textbf{{{s[f'{c}_median_px']:.1f}}}" for s in (original, revised) for c in ("off", "on"))))
    save_table("sweep-table.tex", "@{}lrrrr@{}",
        ["Intervention", r"\off{}", r"\on{} (original)", r"\off{}", r"\on{} (revised)"], rows, midrules=(len(rows) - 1,))

    behaviour_rows = {(s["participant"], s["condition"]): s for s in audit["participant_behaviour"]}
    rows = []
    for pid in ("P1", "P2", "P3", "P4"):
        a, b = behaviour_rows[(pid, "with")], behaviour_rows[(pid, "without")]
        rows.append(table_row(pid,
            f'{number(a["rrt_median_ms"])} ({a["rrt_observed"]}/{a["interventions"]})',
            f'{number(b["rrt_median_ms"])} ({b["rrt_observed"]}/{b["interventions"]})'))
    save_table("behaviour-table.tex", "@{}lrr@{}",
        ["Participant", r"\on{}: median ms ($n/N$)", r"\off{}: median ms ($n/N$)"], rows)

    manifest = {"source": "analysis/outputs/evidence-audit.json",
                "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                "source_review_commit": audit["review_commit"],
                "generated_files": sorted(p.name for p in OUT.glob("*.tex"))}
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Generated {len(manifest['generated_files'])} LaTeX assets from audited evidence.")


if __name__ == "__main__":
    main()
